apiVersion: v1
kind: Service
metadata:
  name: {{ include "hw-auth.fullname" . }}
  namespace: default
  labels:
    {{- include "hw-auth.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: auth-service

---

{{/*apiVersion: v1*/}}
{{/*kind: Service*/}}
{{/*metadata:*/}}
{{/*  name: {{ include "hw-auth.fullname" . }}*/}}
{{/*  namespace: default*/}}
{{/*spec:*/}}
{{/*  type: ExternalName*/}}
{{/*  externalName: auth-hw-auth.default.svc.cluster.local*/}}