apiVersion: v1
kind: Service
metadata:
  name: {{ include "hw-user.fullname" . }}
  namespace: default
  labels:
    {{- include "hw-user.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: users-service
